<?php

namespace ContainerPgpkAu2;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersonService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.A7uOTdJ.App\Entity\Person' shared service.
     *
     * @return \App\Entity\Person
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.A7uOTdJ": it needs an instance of "App\\Entity\\Person" but this type has been excluded in "config/services.yaml".');
    }
}
