<?php

namespace ContainerFuHxWce;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSponsorTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\SponsorType' shared autowired service.
     *
     * @return \App\Form\SponsorType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/SponsorType.php';

        return $container->privates['App\\Form\\SponsorType'] = new \App\Form\SponsorType();
    }
}
