<?php

namespace ContainerJBmg2x0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_33yFkNYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.33yFkNY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.33yFkNY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'administrator' => ['privates', '.errored..service_locator.33yFkNY.App\\Entity\\Administrator', NULL, 'Cannot autowire service ".service_locator.33yFkNY": it needs an instance of "App\\Entity\\Administrator" but this type has been excluded in "config/services.yaml".'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'administrator' => 'App\\Entity\\Administrator',
            'manager' => '?',
        ]);
    }
}
