<?php

namespace ContainerJBmg2x0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequest2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zxQ8fho.App\Entity\Request' shared service.
     *
     * @return \App\Entity\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.zxQ8fho": it needs an instance of "App\\Entity\\Request" but this type has been excluded in "config/services.yaml".');
    }
}
