<?php

namespace ContainerH4v9ZC1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AMfIQn5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aMfIQn5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aMfIQn5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'student' => ['privates', '.errored..service_locator.aMfIQn5.App\\Entity\\Student', NULL, 'Cannot autowire service ".service_locator.aMfIQn5": it needs an instance of "App\\Entity\\Student" but this type has been excluded in "config/services.yaml".'],
        ], [
            'student' => 'App\\Entity\\Student',
        ]);
    }
}
