<?php

<<<<<<<< HEAD:var/cache/dev/ContainerUbhf1M9/get_ServiceLocator_MPUuYf0Service.php
namespace ContainerUbhf1M9;
========
namespace ContainerPgpkAu2;

>>>>>>>> 6a6f802302f86a9a99b8b4be4a8dd434c3d3744f:var/cache/dev/ContainerPgpkAu2/get_ServiceLocator_MPUuYf0Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MPUuYf0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MPUuYf0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MPUuYf0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sponsorRepository' => ['privates', 'App\\Repository\\SponsorRepository', 'getSponsorRepositoryService', true],
        ], [
            'sponsorRepository' => 'App\\Repository\\SponsorRepository',
        ]);
    }
}
