<?php

<<<<<<<< HEAD:var/cache/dev/ContainerUbhf1M9/getSponsorshipService.php
namespace ContainerUbhf1M9;
========
namespace ContainerPgpkAu2;

>>>>>>>> 6a6f802302f86a9a99b8b4be4a8dd434c3d3744f:var/cache/dev/ContainerPgpkAu2/getSponsorshipService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSponsorshipService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.A1WuIv..App\Entity\Sponsorship' shared service.
     *
     * @return \App\Entity\Sponsorship
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.A1WuIv.": it needs an instance of "App\\Entity\\Sponsorship" but this type has been excluded in "config/services.yaml".');
    }
}
