framework:
    workflows:
        sponsoring_process:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'state'

            supports:
                - App\Entity\Sponsorship
            initial_marking: !php/const App\Entity\SponsorshipState::STATE_INITIALIZED
            places:
                - !php/const App\Entity\SponsorshipState::STATE_INITIALIZED                 # Les différents parrainage possible sont créé
                - !php/const App\Entity\SponsorshipState::STATE_MATCH                       # L'admin valide le parrainage
                - !php/const App\Entity\SponsorshipState::STATE_SPONSOR_APPROVED            # Le sponsor confirme la prise de contact
                - !php/const App\Entity\SponsorshipState::STATE_STUDENT_APPROVED            # L'étudiant valide la prise de contact
                - !php/const App\Entity\SponsorshipState::STATE_SPONSORSHIP                 # La deuxième personne valide la prise de contact
                - !php/const App\Entity\SponsorshipState::STATE_ENDED                       # Le parrainage a pris fin

            transitions:
                !php/const App\Entity\SponsorshipTransition::TRANSITION_TO_MATCH:
                    from: !php/const App\Entity\SponsorshipState::STATE_INITIALIZED
                    to: !php/const App\Entity\SponsorshipState::STATE_MATCH


                !php/const App\Entity\SponsorshipTransition::TRANSITION_ST_APPROVE:
                    from: !php/const App\Entity\SponsorshipState::STATE_MATCH
                    to: !php/const App\Entity\SponsorshipState::STATE_STUDENT_APPROVED
                !php/const App\Entity\SponsorshipTransition::TRANSITION_SP_APPROVE:
                    from: !php/const App\Entity\SponsorshipState::STATE_MATCH
                    to: !php/const App\Entity\SponsorshipState::STATE_SPONSOR_APPROVED


                !php/const App\Entity\SponsorshipTransition::TRANSITION_TO_SPONSORSHIP:
                    from: [!php/const App\Entity\SponsorshipState::STATE_STUDENT_APPROVED, !php/const App\Entity\SponsorshipState::STATE_SPONSOR_APPROVED]
                    to: !php/const App\Entity\SponsorshipState::STATE_SPONSORSHIP


                !php/const App\Entity\SponsorshipTransition::TRANSITION_TO_END:
                    from: [ !php/const App\Entity\SponsorshipState::STATE_MATCH, !php/const App\Entity\SponsorshipState::STATE_STUDENT_APPROVED, !php/const App\Entity\SponsorshipState::STATE_SPONSOR_APPROVED, !php/const App\Entity\SponsorshipState::STATE_SPONSORSHIP]
                    to: !php/const App\Entity\SponsorshipState::STATE_ENDED



