<?php

namespace ContainerHnQs5XM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegisterEventsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\RegisterEvents' shared autowired service.
     *
     * @return \App\Service\RegisterEvents
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/event-manager/src/EventSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/EventSubscriber/EventSubscriberInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/RegisterEvents.php';

        return $container->privates['App\\Service\\RegisterEvents'] = new \App\Service\RegisterEvents();
    }
}
