<?php

namespace ContainerHnQs5XM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSponsorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IMMhoNM.App\Entity\Sponsor' shared service.
     *
     * @return \App\Entity\Sponsor
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.IMMhoNM": it needs an instance of "App\\Entity\\Sponsor" but this type has been excluded in "config/services.yaml".');
    }
}
