<?php

namespace ContainerZ2ucn4l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fgtf4dmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fgtf4dm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fgtf4dm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ApiController::algotest' => ['privates', '.service_locator.xp91Ge6', 'get_ServiceLocator_Xp91Ge6Service', true],
            'App\\Controller\\DashboardController::admin' => ['privates', '.service_locator.XC6.mbn', 'get_ServiceLocator_XC6_MbnService', true],
            'App\\Controller\\DashboardController::createAdmin' => ['privates', '.service_locator..gjCOJy', 'get_ServiceLocator__GjCOJyService', true],
            'App\\Controller\\DashboardController::deleteAdmin' => ['privates', '.service_locator.33yFkNY', 'get_ServiceLocator_33yFkNYService', true],
            'App\\Controller\\DashboardController::index' => ['privates', '.service_locator.PBTVzPc', 'get_ServiceLocator_PBTVzPcService', true],
            'App\\Controller\\DashboardController::match' => ['privates', '.service_locator.A1WuIv.', 'get_ServiceLocator_A1WuIv_Service', true],
            'App\\Controller\\DashboardController::matches' => ['privates', '.service_locator.gvThNC9', 'get_ServiceLocator_GvThNC9Service', true],
            'App\\Controller\\DashboardController::sponsors' => ['privates', '.service_locator.MPUuYf0', 'get_ServiceLocator_MPUuYf0Service', true],
            'App\\Controller\\DashboardController::sponsorship' => ['privates', '.service_locator.C4.Baz6', 'get_ServiceLocator_C4_Baz6Service', true],
            'App\\Controller\\DashboardController::sponsorships' => ['privates', '.service_locator.gvThNC9', 'get_ServiceLocator_GvThNC9Service', true],
            'App\\Controller\\DashboardController::sponsorshipvalidation' => ['privates', '.service_locator.lXwBZ8.', 'get_ServiceLocator_LXwBZ8_Service', true],
            'App\\Controller\\DashboardController::students' => ['privates', '.service_locator.wmzwuy.', 'get_ServiceLocator_Wmzwuy_Service', true],
            'App\\Controller\\DashboardController::user' => ['privates', '.service_locator.A7uOTdJ', 'get_ServiceLocator_A7uOTdJService', true],
            'App\\Controller\\DashboardController::users' => ['privates', '.service_locator.nndhpqw', 'get_ServiceLocator_NndhpqwService', true],
            'App\\Controller\\PermaLinkController::accountinfo' => ['privates', '.service_locator.zxQ8fho', 'get_ServiceLocator_ZxQ8fhoService', true],
            'App\\Controller\\PermaLinkController::emailRedirect' => ['privates', '.service_locator.CkhOV7s', 'get_ServiceLocator_CkhOV7sService', true],
            'App\\Controller\\PermaLinkController::emailRedirectEnd' => ['privates', '.service_locator.CkhOV7s', 'get_ServiceLocator_CkhOV7sService', true],
            'App\\Controller\\PermaLinkController::urlGenerate' => ['privates', '.service_locator.A7uOTdJ', 'get_ServiceLocator_A7uOTdJService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ApiController:algotest' => ['privates', '.service_locator.xp91Ge6', 'get_ServiceLocator_Xp91Ge6Service', true],
            'App\\Controller\\DashboardController:admin' => ['privates', '.service_locator.XC6.mbn', 'get_ServiceLocator_XC6_MbnService', true],
            'App\\Controller\\DashboardController:createAdmin' => ['privates', '.service_locator..gjCOJy', 'get_ServiceLocator__GjCOJyService', true],
            'App\\Controller\\DashboardController:deleteAdmin' => ['privates', '.service_locator.33yFkNY', 'get_ServiceLocator_33yFkNYService', true],
            'App\\Controller\\DashboardController:index' => ['privates', '.service_locator.PBTVzPc', 'get_ServiceLocator_PBTVzPcService', true],
            'App\\Controller\\DashboardController:match' => ['privates', '.service_locator.A1WuIv.', 'get_ServiceLocator_A1WuIv_Service', true],
            'App\\Controller\\DashboardController:matches' => ['privates', '.service_locator.gvThNC9', 'get_ServiceLocator_GvThNC9Service', true],
            'App\\Controller\\DashboardController:sponsors' => ['privates', '.service_locator.MPUuYf0', 'get_ServiceLocator_MPUuYf0Service', true],
            'App\\Controller\\DashboardController:sponsorship' => ['privates', '.service_locator.C4.Baz6', 'get_ServiceLocator_C4_Baz6Service', true],
            'App\\Controller\\DashboardController:sponsorships' => ['privates', '.service_locator.gvThNC9', 'get_ServiceLocator_GvThNC9Service', true],
            'App\\Controller\\DashboardController:sponsorshipvalidation' => ['privates', '.service_locator.lXwBZ8.', 'get_ServiceLocator_LXwBZ8_Service', true],
            'App\\Controller\\DashboardController:students' => ['privates', '.service_locator.wmzwuy.', 'get_ServiceLocator_Wmzwuy_Service', true],
            'App\\Controller\\DashboardController:user' => ['privates', '.service_locator.A7uOTdJ', 'get_ServiceLocator_A7uOTdJService', true],
            'App\\Controller\\DashboardController:users' => ['privates', '.service_locator.nndhpqw', 'get_ServiceLocator_NndhpqwService', true],
            'App\\Controller\\PermaLinkController:accountinfo' => ['privates', '.service_locator.zxQ8fho', 'get_ServiceLocator_ZxQ8fhoService', true],
            'App\\Controller\\PermaLinkController:emailRedirect' => ['privates', '.service_locator.CkhOV7s', 'get_ServiceLocator_CkhOV7sService', true],
            'App\\Controller\\PermaLinkController:emailRedirectEnd' => ['privates', '.service_locator.CkhOV7s', 'get_ServiceLocator_CkhOV7sService', true],
            'App\\Controller\\PermaLinkController:urlGenerate' => ['privates', '.service_locator.A7uOTdJ', 'get_ServiceLocator_A7uOTdJService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ApiController::algotest' => '?',
            'App\\Controller\\DashboardController::admin' => '?',
            'App\\Controller\\DashboardController::createAdmin' => '?',
            'App\\Controller\\DashboardController::deleteAdmin' => '?',
            'App\\Controller\\DashboardController::index' => '?',
            'App\\Controller\\DashboardController::match' => '?',
            'App\\Controller\\DashboardController::matches' => '?',
            'App\\Controller\\DashboardController::sponsors' => '?',
            'App\\Controller\\DashboardController::sponsorship' => '?',
            'App\\Controller\\DashboardController::sponsorships' => '?',
            'App\\Controller\\DashboardController::sponsorshipvalidation' => '?',
            'App\\Controller\\DashboardController::students' => '?',
            'App\\Controller\\DashboardController::user' => '?',
            'App\\Controller\\DashboardController::users' => '?',
            'App\\Controller\\PermaLinkController::accountinfo' => '?',
            'App\\Controller\\PermaLinkController::emailRedirect' => '?',
            'App\\Controller\\PermaLinkController::emailRedirectEnd' => '?',
            'App\\Controller\\PermaLinkController::urlGenerate' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ApiController:algotest' => '?',
            'App\\Controller\\DashboardController:admin' => '?',
            'App\\Controller\\DashboardController:createAdmin' => '?',
            'App\\Controller\\DashboardController:deleteAdmin' => '?',
            'App\\Controller\\DashboardController:index' => '?',
            'App\\Controller\\DashboardController:match' => '?',
            'App\\Controller\\DashboardController:matches' => '?',
            'App\\Controller\\DashboardController:sponsors' => '?',
            'App\\Controller\\DashboardController:sponsorship' => '?',
            'App\\Controller\\DashboardController:sponsorships' => '?',
            'App\\Controller\\DashboardController:sponsorshipvalidation' => '?',
            'App\\Controller\\DashboardController:students' => '?',
            'App\\Controller\\DashboardController:user' => '?',
            'App\\Controller\\DashboardController:users' => '?',
            'App\\Controller\\PermaLinkController:accountinfo' => '?',
            'App\\Controller\\PermaLinkController:emailRedirect' => '?',
            'App\\Controller\\PermaLinkController:emailRedirectEnd' => '?',
            'App\\Controller\\PermaLinkController:urlGenerate' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
