<?php

namespace ContainerZ2ucn4l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlgorithmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Algorithm' shared autowired service.
     *
     * @return \App\Service\Algorithm
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Algorithm.php';

        return $container->privates['App\\Service\\Algorithm'] = new \App\Service\Algorithm(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
