<?php

namespace ContainerLsKIVAp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PBTVzPcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PBTVzPc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PBTVzPc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'proposalRepository' => ['privates', 'App\\Repository\\ProposalRepository', 'getProposalRepositoryService', true],
            'requestRepository' => ['privates', 'App\\Repository\\RequestRepository', 'getRequestRepositoryService', true],
            'sponsorshipRepository' => ['privates', 'App\\Repository\\SponsorshipRepository', 'getSponsorshipRepositoryService', true],
        ], [
            'proposalRepository' => 'App\\Repository\\ProposalRepository',
            'requestRepository' => 'App\\Repository\\RequestRepository',
            'sponsorshipRepository' => 'App\\Repository\\SponsorshipRepository',
        ]);
    }
}
