<?php

namespace Container3AsI9xg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xp91Ge6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xp91Ge6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xp91Ge6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'findEntity' => ['privates', 'App\\Service\\FindEntity', 'getFindEntityService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'sponsorRepository' => ['privates', 'App\\Repository\\SponsorRepository', 'getSponsorRepositoryService', true],
            'studentRepository' => ['privates', 'App\\Repository\\StudentRepository', 'getStudentRepositoryService', true],
        ], [
            'findEntity' => 'App\\Service\\FindEntity',
            'manager' => '?',
            'sponsorRepository' => 'App\\Repository\\SponsorRepository',
            'studentRepository' => 'App\\Repository\\StudentRepository',
        ]);
    }
}
