<?php

namespace Container3AsI9xg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFindEntityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\FindEntity' shared autowired service.
     *
     * @return \App\Service\FindEntity
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/FindEntity.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\FindEntity'])) {
            return $container->privates['App\\Service\\FindEntity'];
        }

        return $container->privates['App\\Service\\FindEntity'] = new \App\Service\FindEntity($a);
    }
}
