<?php

namespace Container3AsI9xg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSponsorship3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lXwBZ8..App\Entity\Sponsorship' shared service.
     *
     * @return \App\Entity\Sponsorship
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.lXwBZ8.": it needs an instance of "App\\Entity\\Sponsorship" but this type has been excluded in "config/services.yaml".');
    }
}
