<?php

namespace ContainerMzPulkA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C4_Baz6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C4.Baz6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C4.Baz6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'student' => ['privates', '.errored..service_locator.C4.Baz6.App\\Entity\\Request', NULL, 'Cannot autowire service ".service_locator.C4.Baz6": it needs an instance of "App\\Entity\\Request" but this type has been excluded in "config/services.yaml".'],
        ], [
            'student' => 'App\\Entity\\Request',
        ]);
    }
}
