<?php

namespace ContainerU1CSOq3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sbq0S6XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sbq0S6X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sbq0S6X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\DashboardController::index' => ['privates', '.service_locator.PBTVzPc', 'get_ServiceLocator_PBTVzPcService', true],
            'App\\Controller\\DashboardController::match' => ['privates', '.service_locator.A1WuIv.', 'get_ServiceLocator_A1WuIv_Service', true],
            'App\\Controller\\DashboardController::matches' => ['privates', '.service_locator.gvThNC9', 'get_ServiceLocator_GvThNC9Service', true],
            'App\\Controller\\DashboardController::user' => ['privates', '.service_locator.A7uOTdJ', 'get_ServiceLocator_A7uOTdJService', true],
            'App\\Controller\\DashboardController::users' => ['privates', '.service_locator.nndhpqw', 'get_ServiceLocator_NndhpqwService', true],
            'App\\Controller\\SponsorController::index' => ['privates', '.service_locator.MPUuYf0', 'get_ServiceLocator_MPUuYf0Service', true],
            'App\\Controller\\SponsorController::show' => ['privates', '.service_locator.IMMhoNM', 'get_ServiceLocator_IMMhoNMService', true],
            'App\\Controller\\SponsorshipController::sponsorship' => ['privates', '.service_locator.64IM_Lz', 'get_ServiceLocator_64IMLzService', true],
            'App\\Controller\\SponsorshipController::sponsorships' => ['privates', '.service_locator.gvThNC9', 'get_ServiceLocator_GvThNC9Service', true],
            'App\\Controller\\SponsorshipController::sponsorshipvalidation' => ['privates', '.service_locator.lXwBZ8.', 'get_ServiceLocator_LXwBZ8_Service', true],
            'App\\Controller\\StudentController::index' => ['privates', '.service_locator.wmzwuy.', 'get_ServiceLocator_Wmzwuy_Service', true],
            'App\\Controller\\StudentController::show' => ['privates', '.service_locator.aMfIQn5', 'get_ServiceLocator_AMfIQn5Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\DashboardController:index' => ['privates', '.service_locator.PBTVzPc', 'get_ServiceLocator_PBTVzPcService', true],
            'App\\Controller\\DashboardController:match' => ['privates', '.service_locator.A1WuIv.', 'get_ServiceLocator_A1WuIv_Service', true],
            'App\\Controller\\DashboardController:matches' => ['privates', '.service_locator.gvThNC9', 'get_ServiceLocator_GvThNC9Service', true],
            'App\\Controller\\DashboardController:user' => ['privates', '.service_locator.A7uOTdJ', 'get_ServiceLocator_A7uOTdJService', true],
            'App\\Controller\\DashboardController:users' => ['privates', '.service_locator.nndhpqw', 'get_ServiceLocator_NndhpqwService', true],
            'App\\Controller\\SponsorController:index' => ['privates', '.service_locator.MPUuYf0', 'get_ServiceLocator_MPUuYf0Service', true],
            'App\\Controller\\SponsorController:show' => ['privates', '.service_locator.IMMhoNM', 'get_ServiceLocator_IMMhoNMService', true],
            'App\\Controller\\SponsorshipController:sponsorship' => ['privates', '.service_locator.64IM_Lz', 'get_ServiceLocator_64IMLzService', true],
            'App\\Controller\\SponsorshipController:sponsorships' => ['privates', '.service_locator.gvThNC9', 'get_ServiceLocator_GvThNC9Service', true],
            'App\\Controller\\SponsorshipController:sponsorshipvalidation' => ['privates', '.service_locator.lXwBZ8.', 'get_ServiceLocator_LXwBZ8_Service', true],
            'App\\Controller\\StudentController:index' => ['privates', '.service_locator.wmzwuy.', 'get_ServiceLocator_Wmzwuy_Service', true],
            'App\\Controller\\StudentController:show' => ['privates', '.service_locator.aMfIQn5', 'get_ServiceLocator_AMfIQn5Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\DashboardController::index' => '?',
            'App\\Controller\\DashboardController::match' => '?',
            'App\\Controller\\DashboardController::matches' => '?',
            'App\\Controller\\DashboardController::user' => '?',
            'App\\Controller\\DashboardController::users' => '?',
            'App\\Controller\\SponsorController::index' => '?',
            'App\\Controller\\SponsorController::show' => '?',
            'App\\Controller\\SponsorshipController::sponsorship' => '?',
            'App\\Controller\\SponsorshipController::sponsorships' => '?',
            'App\\Controller\\SponsorshipController::sponsorshipvalidation' => '?',
            'App\\Controller\\StudentController::index' => '?',
            'App\\Controller\\StudentController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\DashboardController:index' => '?',
            'App\\Controller\\DashboardController:match' => '?',
            'App\\Controller\\DashboardController:matches' => '?',
            'App\\Controller\\DashboardController:user' => '?',
            'App\\Controller\\DashboardController:users' => '?',
            'App\\Controller\\SponsorController:index' => '?',
            'App\\Controller\\SponsorController:show' => '?',
            'App\\Controller\\SponsorshipController:sponsorship' => '?',
            'App\\Controller\\SponsorshipController:sponsorships' => '?',
            'App\\Controller\\SponsorshipController:sponsorshipvalidation' => '?',
            'App\\Controller\\StudentController:index' => '?',
            'App\\Controller\\StudentController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
