<?php

namespace ContainerEgPIgsd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JhIFVTiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JhIFVTi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JhIFVTi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sponsorRepository' => ['privates', 'App\\Repository\\SponsorRepository', 'getSponsorRepositoryService', true],
            'sponsorshipRepository' => ['privates', 'App\\Repository\\SponsorshipRepository', 'getSponsorshipRepositoryService', true],
            'studentRepository' => ['privates', 'App\\Repository\\StudentRepository', 'getStudentRepositoryService', true],
        ], [
            'sponsorRepository' => 'App\\Repository\\SponsorRepository',
            'sponsorshipRepository' => 'App\\Repository\\SponsorshipRepository',
            'studentRepository' => 'App\\Repository\\StudentRepository',
        ]);
    }
}
