<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Request extends \App\Entity\Request implements \Doctrine\Persistence\Proxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'App\\Entity\\Lead'."\0".'activity' => ['App\\Entity\\Lead', 'activity', null],
        "\0".'App\\Entity\\Lead'."\0".'city' => ['App\\Entity\\Lead', 'city', null],
        "\0".'App\\Entity\\Lead'."\0".'civility' => ['App\\Entity\\Lead', 'civility', null],
        "\0".'App\\Entity\\Lead'."\0".'id' => ['App\\Entity\\Lead', 'id', null],
        "\0".'App\\Entity\\Lead'."\0".'languages' => ['App\\Entity\\Lead', 'languages', null],
        "\0".'App\\Entity\\Lead'."\0".'person' => ['App\\Entity\\Lead', 'person', null],
        "\0".'App\\Entity\\Lead'."\0".'state' => ['App\\Entity\\Lead', 'state', null],
        "\0".'App\\Entity\\Lead'."\0".'wishes' => ['App\\Entity\\Lead', 'wishes', null],
        "\0".parent::class."\0".'curriculum' => [parent::class, 'curriculum', null],
        "\0".parent::class."\0".'sponsorship' => [parent::class, 'sponsorship', null],
        'activity' => ['App\\Entity\\Lead', 'activity', null],
        'city' => ['App\\Entity\\Lead', 'city', null],
        'civility' => ['App\\Entity\\Lead', 'civility', null],
        'curriculum' => [parent::class, 'curriculum', null],
        'id' => ['App\\Entity\\Lead', 'id', null],
        'languages' => ['App\\Entity\\Lead', 'languages', null],
        'person' => ['App\\Entity\\Lead', 'person', null],
        'sponsorship' => [parent::class, 'sponsorship', null],
        'state' => ['App\\Entity\\Lead', 'state', null],
        'wishes' => ['App\\Entity\\Lead', 'wishes', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".'App\\Entity\\Lead'."\0".'id' => true,
            '__isCloning' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
