<?php

namespace ContainerJXXTvxx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSponsorshipService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.A1WuIv..App\Entity\Sponsorship' shared service.
     *
     * @return \App\Entity\Sponsorship
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.A1WuIv.": it needs an instance of "App\\Entity\\Sponsorship" but this type has been excluded in "config/services.yaml".');
    }
}
