<?php

namespace ContainerAmAZmdt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ACYCZkEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aCYCZkE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aCYCZkE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sponsorship' => ['privates', '.errored..service_locator.aCYCZkE.App\\Entity\\Sponsorship', NULL, 'Cannot autowire service ".service_locator.aCYCZkE": it needs an instance of "App\\Entity\\Sponsorship" but this type has been excluded in "config/services.yaml".'],
            'sponsorshipRepository' => ['privates', 'App\\Repository\\SponsorshipRepository', 'getSponsorshipRepositoryService', true],
        ], [
            'sponsorship' => 'App\\Entity\\Sponsorship',
            'sponsorshipRepository' => 'App\\Repository\\SponsorshipRepository',
        ]);
    }
}
