<?php

namespace ContainerCuKG2WV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSponsorshipControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SponsorshipController' shared autowired service.
     *
     * @return \App\Controller\SponsorshipController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/SponsorshipController.php';

        $container->services['App\\Controller\\SponsorshipController'] = $instance = new \App\Controller\SponsorshipController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\SponsorshipController', $container));

        return $instance;
    }
}
