<?php

namespace ContainerGeR0BM4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_FisQPceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.fisQPce' shared service.
     *
     * @return \App\Service\LeadService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\DashboardController::index()": the $leadService argument is type-hinted with the non-existent class or interface: "App\\Service\\LeadService".');
    }
}
