<?php

namespace ContainerMnovIpm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ExOGs1RService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.exOGs1R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.exOGs1R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'sponsorship' => ['privates', '.errored..service_locator.exOGs1R.App\\Entity\\Sponsorship', NULL, 'Cannot autowire service ".service_locator.exOGs1R": it needs an instance of "App\\Entity\\Sponsorship" but this type has been excluded in "config/services.yaml".'],
            'workflow' => ['privates', '.errored..service_locator.exOGs1R.Symfony\\Component\\Workflow\\WorkflowInterface', NULL, 'Cannot autowire service ".service_locator.exOGs1R": it references interface "Symfony\\Component\\Workflow\\WorkflowInterface" but no such service exists. Available autowiring aliases for this interface are: "$sponsoringProcessStateMachine", "$sponsoringProcess".'],
        ], [
            'entityManager' => '?',
            'sponsorship' => 'App\\Entity\\Sponsorship',
            'workflow' => 'Symfony\\Component\\Workflow\\WorkflowInterface',
        ]);
    }
}
