<?php

namespace ContainerMnovIpm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorkflowInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.exOGs1R.Symfony\Component\Workflow\WorkflowInterface' shared service.
     *
     * @return \Symfony\Component\Workflow\WorkflowInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.exOGs1R": it references interface "Symfony\\Component\\Workflow\\WorkflowInterface" but no such service exists. Available autowiring aliases for this interface are: "$sponsoringProcessStateMachine", "$sponsoringProcess".');
    }
}
