<?php

namespace ContainerCAWSnxQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K6fmpDxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.K6fmpDx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.K6fmpDx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'proposalRepository' => ['privates', 'App\\Repository\\ProposalRepository', 'getProposalRepositoryService', true],
        ], [
            'proposalRepository' => 'App\\Repository\\ProposalRepository',
        ]);
    }
}
