<?php

namespace ContainerCAWSnxQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdministratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.33yFkNY.App\Entity\Administrator' shared service.
     *
     * @return \App\Entity\Administrator
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.33yFkNY": it needs an instance of "App\\Entity\\Administrator" but this type has been excluded in "config/services.yaml".');
    }
}
