<?php

<<<<<<<< HEAD:var/cache/dev/ContainerFmlgJxJ/getSponsoringProcessSubscriberService.php
namespace ContainerFmlgJxJ;
========
namespace ContainerF0uzbxP;

>>>>>>>> 6a6f802302f86a9a99b8b4be4a8dd434c3d3744f:var/cache/dev/ContainerF0uzbxP/getSponsoringProcessSubscriberService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSponsoringProcessSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Event\SponsoringProcessSubscriber' shared autowired service.
     *
     * @return \App\Event\SponsoringProcessSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Event'.\DIRECTORY_SEPARATOR.'SponsoringProcessSubscriber.php';

        $a = ($container->privates['App\\Service\\Mailing'] ?? $container->load('getMailingService'));

        if (isset($container->privates['App\\Event\\SponsoringProcessSubscriber'])) {
            return $container->privates['App\\Event\\SponsoringProcessSubscriber'];
        }

        return $container->privates['App\\Event\\SponsoringProcessSubscriber'] = new \App\Event\SponsoringProcessSubscriber($a, ($container->services['monolog.logger.history'] ?? $container->load('getMonolog_Logger_HistoryService')));
    }
}
