<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZobcZ1w\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZobcZ1w/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZobcZ1w.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZobcZ1w\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZobcZ1w\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZobcZ1w',
    'container.build_id' => '95712f98',
    'container.build_time' => 1688129189,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZobcZ1w');
