<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGcvv1JE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGcvv1JE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGcvv1JE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGcvv1JE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGcvv1JE\App_KernelDevDebugContainer([
    'container.build_hash' => 'Gcvv1JE',
    'container.build_id' => '5ac1ffba',
    'container.build_time' => 1687182573,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGcvv1JE');
