<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_api_sponsor' => [[], ['_controller' => 'App\\Controller\\ApiController::createSponsor'], [], [['text', '/api/sponsor']], [], [], []],
    'app_api_student' => [[], ['_controller' => 'App\\Controller\\ApiController::createStudent'], [], [['text', '/api/student']], [], [], []],
    'app_dashboard' => [[], ['_controller' => 'App\\Controller\\DashboardController::index'], [], [['text', '/']], [], [], []],
    'app_dashboard_users' => [[], ['_controller' => 'App\\Controller\\DashboardController::users'], [], [['text', '/users']], [], [], []],
    'app_dashboard_user' => [['id'], ['_controller' => 'App\\Controller\\DashboardController::user'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], [], []],
    'app_perma_link' => [[], ['_controller' => 'App\\Controller\\PermaLinkController::index'], [], [['text', '/perma/link']], [], [], []],
    'app_sponsor_index' => [[], ['_controller' => 'App\\Controller\\SponsorController::index'], [], [['text', '/sponsor/']], [], [], []],
    'app_sponsor_show' => [['id'], ['_controller' => 'App\\Controller\\SponsorController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/sponsor']], [], [], []],
    'app_sponsorship_sponsorships' => [[], ['_controller' => 'App\\Controller\\SponsorshipController::sponsorships'], [], [['text', '/sponsorships']], [], [], []],
    'app_sponsorship_new' => [['id'], ['_controller' => 'App\\Controller\\SponsorshipController::sponsorship'], [], [['text', '/sponsorship'], ['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], [], []],
    'app_sponsorship_validate' => [['sponsorship'], ['_controller' => 'App\\Controller\\SponsorshipController::sponsorshipvalidation'], [], [['variable', '/', '[^/]++', 'sponsorship', true], ['text', '/validate']], [], [], []],
    'app_dashboard_matches' => [[], ['_controller' => 'App\\Controller\\SponsorshipController::matches'], [], [['text', '/matches']], [], [], []],
    'app_dashboard_match' => [['id'], ['_controller' => 'App\\Controller\\SponsorshipController::match'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/match']], [], [], []],
    'app_student_index' => [[], ['_controller' => 'App\\Controller\\StudentController::index'], [], [['text', '/student/']], [], [], []],
    'app_student_show' => [['id'], ['_controller' => 'App\\Controller\\StudentController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/student']], [], [], []],
];
