<?php

namespace ContainerMQrZ6eo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZxQ8fhoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zxQ8fho' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zxQ8fho'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'personRepository' => ['privates', 'App\\Repository\\PersonRepository', 'getPersonRepositoryService', true],
            'request' => ['privates', '.errored..service_locator.zxQ8fho.App\\Entity\\Request', NULL, 'Cannot autowire service ".service_locator.zxQ8fho": it needs an instance of "App\\Entity\\Request" but this type has been excluded in "config/services.yaml".'],
        ], [
            'personRepository' => 'App\\Repository\\PersonRepository',
            'request' => 'App\\Entity\\Request',
        ]);
    }
}
