<?php

namespace ContainerMQrZ6eo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.CkhOV7s.App\Entity\Lead' shared service.
     *
     * @return \App\Entity\Lead
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.CkhOV7s": it needs an instance of "App\\Entity\\Lead" but this type has been excluded in "config/services.yaml".');
    }
}
